/**
 * @license
 * Copyright (c) 2019 Yohanes Oktavianus Lumentut All Rights Reserved.
 *
 * Use of this source code is governed by an MIT-style license that can be
 * found in the LICENSE file at https://github.com/yohaneslumentut/ng-ripple-module/blob/master/LICENSE
 */

const RIPPLE_TO_CENTER_TRANSFORM = 'translate3d(0px, 0px, 0) scale(1)';
const RIPPLE_LIGHT_BGCOLOR = 'rgba(255,255,255, 0.25)';
const RIPPLE_LIGHT_ACTIVE_BGCOLOR = 'rgba(255,255,255,0.2)';
const RIPPLE_DEFAULT_BGCOLOR = 'rgba(0,0,0,0.07)';
const RIPPLE_DEFAULT_ACTIVE_BGCOLOR =  'rgba(0,0,0,0.05)';
const RIPPLE_FILL_TRANSITION = '750ms linear';
const RIPPLE_SPLASH_TRANSITION = '150ms cubic-bezier(0.2,0.05,0.2,1)';
const RIPPLE_FADE_TRANSITION = '90ms linear';
const RIPPLE_BG_FADE_TRANSITION = '90ms ease-in';
const RIPPLE_ITEM_FILL_TRANSITION = '1500ms linear';
const RIPPLE_ITEM_SPLASH_TRANSITION = '180ms cubic-bezier(0.2,0.05,0.2,1)';
const RIPPLE_ITEM_BGCOLOR = 'rgba(0,0,0,0.05)';
const RIPPLE_ITEM_ACTIVE_BGCOLOR = 'rgba(0,0,0,0.035)';
const RIPPLE_HOST_ACTIVE_SPEED = '200ms';
const RIPPLE_HOST_INACTIVE_SPEED = '350ms';
const RIPPLE_REPEATING_EVENT_LIMIT = 700;
const RIPPLE_TAP_LIMIT = 700;
const RIPPLE_SPLASH_OPACITY = 1;
const RIPPLE_ACTIVE_CLASS = 'activate';
const RIPPLE_EVENT_DELAY = true;
const RIPPLE_EVENT_DELAY_VALUE = 190;
const RIPPLE_BACKGROUND_INCLUDED = true;
const RIPPLE_DISMOUNTING_TIMEOUT = 340;
const RIPPLE_SCALE_INCREASER = 0.015;

export {
  RIPPLE_TO_CENTER_TRANSFORM,
  RIPPLE_LIGHT_BGCOLOR,
  RIPPLE_LIGHT_ACTIVE_BGCOLOR,
  RIPPLE_DEFAULT_BGCOLOR,
  RIPPLE_DEFAULT_ACTIVE_BGCOLOR,
  RIPPLE_FILL_TRANSITION,
  RIPPLE_SPLASH_TRANSITION,
  RIPPLE_FADE_TRANSITION,
  RIPPLE_BG_FADE_TRANSITION,
  RIPPLE_ITEM_FILL_TRANSITION,
  RIPPLE_ITEM_SPLASH_TRANSITION,
  RIPPLE_ITEM_BGCOLOR,
  RIPPLE_ITEM_ACTIVE_BGCOLOR,
  RIPPLE_HOST_ACTIVE_SPEED,
  RIPPLE_HOST_INACTIVE_SPEED,
  RIPPLE_REPEATING_EVENT_LIMIT,
  RIPPLE_TAP_LIMIT,
  RIPPLE_SPLASH_OPACITY,
  RIPPLE_ACTIVE_CLASS,
  RIPPLE_EVENT_DELAY,
  RIPPLE_EVENT_DELAY_VALUE,
  RIPPLE_BACKGROUND_INCLUDED,
  RIPPLE_DISMOUNTING_TIMEOUT,
  RIPPLE_SCALE_INCREASER
};
